services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

volumes:
  db_data: